PointfootCfg:
  loop_frequency: 500
  joint_names:
    - "abad_L_Joint"
    - "hip_L_Joint"
    - "knee_L_Joint"
    - "wheel_L_Joint"
    - "abad_R_Joint"
    - "hip_R_Joint"
    - "knee_R_Joint"
    - "wheel_R_Joint"
  
  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      abad_L_Joint: 0.0
      hip_L_Joint: 0.0
      knee_L_Joint: 0.0
      wheel_L_Joint: 0.0

      abad_R_Joint: 0.0
      hip_R_Joint: 0.0
      knee_R_Joint: 0.0
      wheel_R_Joint: 0.0

  control:
    # PD Drive parameters:
    stiffness: 42.0
    damping: 2.5
    wheel_joint_damping: 0.8
    wheel_joint_torque_limit: 40
    action_scale_pos: 0.25
    action_scale_vel: 5.0
    decimation: 10
    user_torque_limit: 80

  normalization:
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.
    obs_scales:
      lin_vel: 2.0
      ang_vel: 0.25
      dof_pos: 1.0
      dof_vel: 0.05

  size:
    actions_size: 8
    observations_size: 28 # 31
    commands_size: 3
    obs_history_length: 10
    jointpos_idxs: [0, 1, 2, 4, 5, 6]
    encoder_output_size: 3

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  user_cmd_scales:
    lin_vel_x: 1.5
    lin_vel_y: 1.0
    ang_vel_yaw: 0.5

  user_cmd_offsets:
    lin_vel_x: 0.0
    lin_vel_y: 0.0
    ang_vel_yaw: 0.0

  mjlab:
    control:
      action_scale_pos: 0.25
      action_scale_vel: 1.0
    size:
      observations_size: 31
      commands_size: 3
      obs_history_length: 20
      encoder_output_size: 0
    command:
      base_pose_scale_xy: 2.0
      base_se3_decrease_rate: 1.0
      target_orient_x_axis: [1.0, 0.0]
      input_deadband: 0.0
      input_offsets:
        lin_vel_x: 0.0 # 0.0035
        lin_vel_y: 0.0 # 0.01
        ang_vel_yaw: 0.0 # 0.19
      cmd_offsets:
        lin_vel_x: 0.0035
        lin_vel_y: 0.01
        ang_vel_yaw: 0.0
      policy_commands_size: 0
      history_term_dims: [3, 3, 3, 6, 8, 8]
